name: easy_audio_trimmer
description: A Flutter package for trimming audio. This supports retrieving, trimming, and storage of trimmed audio files to the file system.
version: 1.0.1+2
homepage: https://github.com/mayurpitroda96/easy_audio_trimmer

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  audioplayers: ^4.1.0
  ffmpeg_kit_flutter: ^5.1.0-LTS
  flutter:
    sdk: flutter
  intl: ^0.18.1
  path: ^1.8.3
  path_provider: ^2.0.15


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:


